routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	
	$model = isset($_GET['car-model'])?$_GET['car-model']:'';
	if($model == 'all'){
		$cars = DB::table('Car_model')->get();/*get all car recoed from database*/
	}elseif($model!=''){
		$cars = DB::table('Car_model')->where('car_brand',$model)->get();/*get selected car recoed from database*/
	}else{
		$cars = DB::table('Car_model')->get();/*get all car recoed from database*/
	}	
	//dd($cars);
    return view('welcome',['cars'=>$cars]);
});


//authentication route
Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');


// Route::get('/cart', 'CartController@index')->name('cart');
// Route::any('/cart/add', 'CartController@add')->name('cart.add');
/*group route*/

Route::prefix('cart')->group(function() {
	Route::any('/add', 'CartController@add')->name('cart.add');
	Route::any('/viewCart', 'CartController@viewCart')->name('cart.viewCart');
	Route::any('/edit', 'CartController@edit')->name('cart.edit');
	Route::any('/delete/{id}', 'CartController@delete')->name('cart.delete');
});

Route::get('/checkout', 'CheckoutController@checkout')->name('checkout');
Route::post('/cartSave', 'CheckoutController@cartSave')->name('cartSave');

/*order*/

Route::get('/order', 'OrderController@index')->name('order');


/*
-----------------------------------------------
 admin routes
-------------------------------------------------
*/
Route::prefix('admin')->namespace('Auth\Admin')->group(function(){
	// Authentication Routes...
	Route::get('/', 'LoginController@showLoginForm')->name('admin.login');
	Route::post('/login', 'LoginController@login');
	Route::post('/logout', 'LoginController@logout')->name('admin.logout');
	
	// Password Reset Routes... copiedfrom router.php
    Route::get('password/reset', 'Passwords\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('password/email', 'Passwords\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    
    Route::get('password/reset/{token}', 'Passwords\ResetPasswordController@showResetForm')->name('admin.password.reset');
    Route::post('password/reset', 'Passwords\ResetPasswordController@reset');
});

Route::prefix('admin')->namespace('Admin')->group(function(){
	//admin authuorization routes
    Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
    Route::get('order', 'DashboardController@order')->name('admin.order');
    Route::get('order/{id}', 'ProcessOrderController@orderDetails');
    Route::get('profile', 'DashboardController@profile')->name('admin.profile');
    Route::post('profile/{id}', 'DashboardController@updateProfile');
    // car resource route
    Route::resource('cars', 'CarController');
    
    
       
});

app/Car.php
<?php

namespace Car;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    protected $table = 'car_model';
	protected $primaryKey = 'id';
}

app/Http/Controllers/Admin/CarController.php
<?php

namespace Car\Http\Controllers\Admin;

//use Car\Car;

use DB;
use Auth;
use Validator;
use Session;
use Car\model\carModel as Car;
use Illuminate\Http\Request;
use Car\Http\Controllers\Controller;

class CarController extends Controller
{
    
    public function __construct(){
        //dd($guard);
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {       
        $this->data['cars'] = Car::simplePaginate(5);
        //$this->data['cars'] = Car::paginate(5);
        $this->data['count'] = Car::all()->count();
        /*echo "<pre>";
        print_r($this->data['cars']);
        exit;*/
        //return $this->data;
        return view('admin.car.index',$this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.car.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->post());
        if($request->submit){
            //dd($request->post());      
            $validator = Validator::make($request->all(),
                [                
                    'car_brand'=>'required|regex:/(^[a-zA-Z ]+$)+/',            
                    'car_name'=>'required|regex:/(^[a-zA-Z ]+$)+/|unique:car_model',            
                    'car_image'=>'required',            
                    'car_price'=>'required|regex:/(^[0-9 ]+$)+/',           
                ],
                [
                    'car_brand.required' => 'The Car-Brand name is required.',
                    'car_name.required' => 'The Car name is required.',
                    'car_image.required' => 'The Car Image is required.',
                    'car_price.required' => 'The Car price is required.',
                    'car_brand.regex' => 'The Car-Brand allowed alphabates only.',
                    'car_name.regex' => 'The Car-name allowed alphabates only.',                    
                    'car_price.regex' => 'The Car-price allowed number only.',
                    
                ]);
            if($validator->fails()) 
            {
                //echo "sdfgh";exit;
                return redirect()
                ->back()
                ->withErrors($validator)
                ->withInput();
            }else{
                //procedd to save the data
                //echo "<pre>";print_r($request->post());
                //echo "<pre>";print_r(Session::get('cart'));exit;
                DB::beginTransaction();
                try{
                     $tblProduct = [
                        'car_brand' => $request->car_brand,
                        'car_name' => $request->car_name,
                        'car_price' => $request->car_price,
                    ]; 
                    /*insert product and get insert id*/                   
                    $lastinsertid = Car::insertGetId($tblProduct);

                    /*upload car image*/
                    $image = $request->file('car_image');
                    $input['car_image'] = $lastinsertid.'.'.$image->getClientOriginalExtension();
                    $destinationPath = public_path('/assets/car');
                    $image->move($destinationPath, $input['car_image']);   

                    /*update image name*/
                    $updateProductImg = [
                        'car_image'=> $input['car_image'],                       
                    ];
                    $lastupdate = Car::where('id',$lastinsertid)->update($updateProductImg);

                    if($lastinsertid && $lastupdate){
                        /*all insert done successfully*/
                        DB::commit();                                            
                        return redirect()
                            ->route('cars.index')
                            ->with('status','Car has been saved successfuly.');
                    }
                }catch(\Exception $e) {
                    dd($e);
                    DB::rollback(); 
                    return back();
                }
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \Car\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function show(Car $car)
    {
        
        /*dd($car);
        echo "show";exit;*/
        return response()->json(['car'=>$car]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Car\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function edit(Car $car)
    {
        /*
        echo $car->car_brand;
        dd($car);
        echo "edit";exit;
        */
        //return $car;
        return view('admin.car.edit',['car'=>$car]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Car\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Car $car)
    {
        
        /*echo $car->id;
        dd($request);
        echo "update";exit;*/
        if($request->submit){
            $validator = Validator::make($request->all(),
                [                
                    'car_brand'=>'required|regex:/(^[a-zA-Z ]+$)+/',            
                    'car_name'=>'required|regex:/(^[a-zA-Z0-9 -]+$)+/',
                    'car_price'=>'required|regex:/(^[0-9 ]+$)+/',           
                ],
                [
                    'car_brand.required' => 'The Car-Brand name is required.',
                    'car_name.required' => 'The Car name is required.',
                    'car_price.required' => 'The Car price is required.',
                    'car_brand.regex' => 'The Car-Brand allowed alphabates only.',
                    'car_name.regex' => 'The Car-name allowed alphabates only.',                    
                    'car_price.regex' => 'The Car-price allowed number only.',
                ]
            );            
            if($validator->fails()) 
            {                
                return redirect()
                ->back()
                ->withErrors($validator)
                ->withInput();
            }else{
                    
                /*$tblProduct = [
                    'car_brand' => $request->car_brand,
                    'car_name' => $request->car_name,
                    'car_price' => $request->car_price,
                ];*/ 
                $car->car_brand = $request->car_brand;
                $car->car_name  = $request->car_name;
                $car->car_price = $request->car_price;
                $car->save();                

                //remove file
                if(\File::exists(public_path('/assets/car'.$car->car_image))){
                  \File::delete(public_path('/assets/car'.$car->car_image));
                }
                //upload file
                if($request->hasFile('car_image')){

                    $image = $request->file('car_image');
                    $input['car_image'] = $car->id.'.'.$image->getClientOriginalExtension();
                    $destinationPath = public_path('/assets/car');
                    $image->move($destinationPath, $input['car_image']); 
                }                                               
                return redirect()
                    ->route('cars.index')
                    ->with('status','Car has been updated successfuly.');
            }
        }        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Car\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car)
    {
        /*echo "destroy";
        echo $car->id;
        dd($car);
        echo "destroy";exit;*/
        $car->delete();
        return redirect()
            ->route('cars.index')
            ->with('status','Car has been deleted successfuly.');
    }
}

resources/views/admin/car/create.blade.php
@include('admin.layouts.common.header')
@include('admin.layouts.common.sidebar')
    <!-- partial -->
    <div class="main-panel">
		<div class="content-wrapper">
			<!-- Page Title Header Starts-->
			<div class="row page-title-header">
				<div class="col-12">
					<div class="page-header">						
						<div class="quick-link-wrapper w-100 d-md-flex flex-md-wrap">
							<ul class="quick-links">
								<li>
									<a href="{{route('cars.index')}}">Car</a>
								</li>
								<li>
									<a href="{{route('cars.create')}}">Create</a>
								</li>
							</ul>
							<!-- <ul class="quick-links ml-auto">
								<li><a href="#">Settings</a>
								</li>
								<li><a href="#">Analytics</a>
								</li>
								<li><a href="#">Watchlist</a>
								</li>
							</ul> -->
						</div>
					</div>
				</div>
			</div>
			<div class="col-12 grid-margin">
            <div class="card">
              	<div class="card-body">
                <mark class="bg-warning text-white">Car Add Form</mark>
                <form class="form-sample" method="POST" action="{{route('cars.store')}}" enctype="multipart/form-data">
                	{{csrf_field()}}
                  <p class="text-success">Provide Car infomation </p>
                  <div class="row">
	                    <div class="col-md-6 ">
	                      <div class="form-group row {{ $errors->has('car_brand') ? ' has-error' : '' }}">
	                        <label class="col-sm-3 col-form-label">Car Brand</label>
	                        <div class="col-sm-9">
	                          <select class="form-control" name="car_brand">
	                          	<option value="">Select Car Brand</option>
	                          	@foreach(['MARUTI'=>'MARUTI','MAHINDRA'=>'MAHINDRA','BMW'=>'BMW','TATA'=>'TATA','TOYOTA'=>'TOYOTA'] as $key=>$val)
	                          		<option value="{{$key}}" {{old('car_brand') == $key? "selected":""}}>{{$val}}</option>
	                          	@endforeach	                           
	                          </select>
	                          <span class="text-danger">{{$errors->first('car_brand')}}</span>
	                        </div>
	                      </div>
	                    </div>
	                    <div class="col-md-6">
	                      <div class="form-group row{{ $errors->has('car_name') ? ' has-error' : '' }}">
	                        <label class="col-sm-3 col-form-label">Car Name</label>
	                        <div class="col-sm-9">
	                          <input class="form-control" placeholder="Car Name" name="car_name" value="{{ old('car_name') }}">
	                          <span class="text-danger">{{$errors->first('car_name')}}</span>
	                        </div>
	                      </div>
	                    </div>
                  	</div>
                  	<div class="row">
	                    <div class="col-md-6 ">
	                      <div class="form-group row {{ $errors->has('car_image') ? ' has-error' : '' }}">
	                        <label class="col-sm-3 col-form-label">Choose Image</label>
	                        <div class="col-sm-9">
	                          <input type="file" name="car_image"class="form-control file-upload-info" placeholder="Upload Image" onchange="readURL(this);">
	                          <span class="text-danger">{{$errors->first('car_image')}}</span>
	                        </div>
	                      </div>
	                    </div>
	                    <div class="col-md-6">
	                      <div class="form-group row {{ $errors->has('car_price') ? ' has-error' : '' }}">
	                        <label class="col-sm-3 col-form-label">Car Price</label>
	                        <div class="col-sm-9">
	                          <input type="text" class="form-control"  name="car_price" placeholder="Car Price" value="{{ old('car_price') }}">
	                          <span class="text-danger">{{$errors->first('car_price')}}</span>
	                        </div>
	                      </div>
	                    </div>
                  	</div>
                  	<div class="row">
                  		<div class="col-md-5 pull-right">
                  			<img src="{{URL('assets/profile/no-image.png')}}" alt="demo" id="demoCarImg" >
                  		</div>
                  		<div class="col-md-7 pull-right">
                  			<input type="submit" class="btn btn-outline-success btn-lg" name="submit" value="Save Car">
                  		</div>
                  	</div>                  	
                </form>
              	</div>
            </div>
        </div>	
	</div>
	<style type="text/css">
		#demoCarImg{
			height:100px;
			width:100px;
			border:1px solid #123;
			border-radius: 5px;
		}
		
	</style>
	<script type="text/javascript">
		function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#demoCarImg')
                    .attr('src', e.target.result)
                    .width(100)
                    .height(100);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
	</script>
    <!-- partial -->       
@include('admin.layouts.common.footer')

resources/views/admin/car/edit.blade.php
@include('admin.layouts.common.header')
@include('admin.layouts.common.sidebar')
    <!-- partial -->
    <div class="main-panel">
		<div class="content-wrapper">
			<!-- Page Title Header Starts-->
			<div class="row page-title-header">
				<div class="col-12">
					<div class="page-header">						
						<div class="quick-link-wrapper w-100 d-md-flex flex-md-wrap">
							<ul class="quick-links">
								<li>
									<a href="{{route('cars.index')}}">Car</a>
								</li>
								<li>
									<a href="{{route('cars.edit',$car->id)}}">Edit</a>
								</li>
							</ul>
							<!-- <ul class="quick-links ml-auto">
								<li><a href="#">Settings</a>
								</li>
								<li><a href="#">Analytics</a>
								</li>
								<li><a href="#">Watchlist</a>
								</li>
							</ul> -->
						</div>
					</div>
				</div>
			</div>
			<!-- {{$car}} -->
			<div class="col-12 grid-margin">
            <div class="card">
              	<div class="card-body">
                <mark class="bg-warning text-white">Car Edit Form</mark>
                <form class="form-sample" method="POST" action="{{route('cars.update',$car->id)}}" enctype="multipart/form-data">
                	{{csrf_field()}}
                	<input type="hidden" name="_method" value="PATCH">
                  <p class="text-success">Update Car infomation </p>
                  <div class="row">
	                    <div class="col-md-6 ">
	                      <div class="form-group row {{ $errors->has('car_brand') ? ' has-error' : '' }}">
	                        <label class="col-sm-3 col-form-label">Car Brand</label>
	                        <div class="col-sm-9">
	                          <select class="form-control" name="car_brand">
	                          	<option value="">Select Car Brand</option>
	                          	@foreach(['MARUTI'=>'MARUTI','MAHINDRA'=>'MAHINDRA','BMW'=>'BMW','TATA'=>'TATA','TOYOTA'=>'TOYOTA'] as $key=>$val)
	                          		<option value="{{$key}}" {{$car->car_brand == $key? "selected":""}}>{{$val}}</option>
	                          	@endforeach	                           
	                          </select>
	                          <span class="text-danger">{{$errors->first('car_brand')}}</span>
	                        </div>
	                      </div>
	                    </div>
	                    <div class="col-md-6">
	                      <div class="form-group row{{ $errors->has('car_name') ? ' has-error' : '' }}">
	                        <label class="col-sm-3 col-form-label">Car Name</label>
	                        <div class="col-sm-9">
	                          <input class="form-control" placeholder="Car Name" name="car_name" value="{{ $car->car_name }}">
	                          <span class="text-danger">{{$errors->first('car_name')}}</span>
	                        </div>
	                      </div>
	                    </div>
                  	</div>
                  	<div class="row">
	                    <div class="col-md-6 ">
	                      <div class="form-group row {{ $errors->has('car_image') ? ' has-error' : '' }}">
	                        <label class="col-sm-3 col-form-label">Choose Image</label>
	                        <div class="col-sm-9">
	                          <input type="file" name="car_image"class="form-control file-upload-info" placeholder="Upload Image" onchange="readURL(this);">
	                          <span class="text-danger">{{$errors->first('car_image')}}</span>
	                        </div>
	                      </div>
	                    </div>
	                    <div class="col-md-6">
	                      <div class="form-group row {{ $errors->has('car_price') ? ' has-error' : '' }}">
	                        <label class="col-sm-3 col-form-label">Car Price</label>
	                        <div class="col-sm-9">
	                          <input type="text" class="form-control"  name="car_price" placeholder="Car Price" value="{{ $car->car_price }}">
	                          <span class="text-danger">{{$errors->first('car_price')}}</span>
	                        </div>
	                      </div>
	                    </div>
                  	</div>

                  	<div class="row">
                  		<div class="col-md-5 pull-right">
                  			@if(file_exists( public_path().'/assets/car/'.$car->car_image))

		                        <img src="{{asset('assets/car/'.$car->car_image)}}" alt="demo" id="demoCarImg" >

		                    @else

		                        <img src="{{asset('assets/profile/no-image.png')}}" alt="demo" id="demoCarImg" >

		                    @endif
                  		</div>
                  		<div class="col-md-7 pull-right">
                  			<input type="submit" class="btn btn-outline-success btn-lg" name="submit" value="Update Car">
                  		</div>
                  	</div>                  	
                </form>
              	</div>
            </div>
        </div>	
	</div>
	<style type="text/css">
		#demoCarImg{
			height:100px;
			width:100px;
			border:1px solid #123;
			border-radius: 5px;
		}
		
	</style>
	<script type="text/javascript">
		function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#demoCarImg')
                    .attr('src', e.target.result)
                    .width(100)
                    .height(100);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
	</script>
    <!-- partial -->       
@include('admin.layouts.common.footer')

resources/views/admin/car/index.blade.php
@include('admin.layouts.common.header')
@include('admin.layouts.common.sidebar')
    <!-- partial -->
    <div class="main-panel">
		<div class="content-wrapper">
			<!-- Page Title Header Starts-->
			<div class="row page-title-header">
				<div class="col-12">
					<div class="page-header">						
						<div class="quick-link-wrapper w-100 d-md-flex flex-md-wrap">
							<ul class="quick-links">
								<li><a href="{{route('cars.index')}}">Car</a>
								</li>
							</ul>
							<!-- <ul class="quick-links ml-auto">
								<li><a href="#">Settings</a>
								</li>
								<li><a href="#">Analytics</a>
								</li>
								<li><a href="#">Watchlist</a>
								</li>
							</ul> -->
						</div>
					</div>
				</div>
				<div class="col-md-12">
					
				</div>
			</div>
			<!-- Page Title Header Ends-->
			<div class="row">
				
			</div>
			<!-- {{!!$cars!!}} -->
			@if(Session::get('status'))
                <div class="alert alert-success" role="alert">
                  <b>{{Session::get('status')}}<b>
                </div>
            @endif
			<div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title pull-right">Car List</h4> 
                    <a href="{{route('cars.create')}}" class="pull-left">                    	
                    	<button type="button" class="btn btn-sm btn-success">ADD Car</button>
                    </a>  
                    
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th> Sl </th>
                          <th> Car Image </th>
                          <th> Car name </th>
                          <th> Car Brand </th>
                          <th> Car Price </th>
                          <th> Action </th>
                        </tr>
                      </thead>
                      <tbody>
                        @php
	                        $i=1;	                       
                   		@endphp
                        @foreach($cars as $car)
                        	<tr>
                        		<td> {{$i}} </td>
	                          	<td class="py-1">
	                            	<img src="{{URL('assets/car')}}/{{$car->car_image}}" alt="image">
	                        	</td>
	                          	<td> {{$car['car_name']}} </td>
	                          	<td>{{$car['car_brand']}}</td>
	                          	<td> {{$car['car_price']}} </td>	                         
	                          	<td> 
	                          		<a href="javascript:void(0);">
			                    		<button type="button" class="btn btn-xs btn-outline-primary veiwCar" data-url="{{route('cars.show',$car->id)}}">View</button>
			                    	</a>
			                    	<a href="{{route('cars.edit',$car->id)}}" onclick="return confirm('Are you sure to Edit ??');">
			                    		<button type="button" class="btn btn-xs btn-outline-success">Edit</button>
			                    	</a>
			                    	<!-- <a href="{{route('cars.create')}}">
			                    		<button type="button" class="btn btn-outline-danger">Delete</button>
			                    	</a> -->
			                    	<a href="javascript:void(0);">
			                    		<form action="{{ route('cars.destroy',$car->id) }}" method="POST"
			                    			onsubmit="return confirm('Are you sure to delete ??');">
										    <input type="hidden" name="_method" value="DELETE">
										    <input type="hidden" name="_token" value="{{ csrf_token() }}">
										    <input type="submit" class="btn btn-xs btn-outline-danger" value="Delete">
									</form>
			                    	</a>
			                    	<!-- <a href="javascript:void(0);" onclick="event.preventDefault();
                                             document.getElementById('destroy-form').submit();">
                                    <button type="button" class="btn btn-outline-danger">Delete</button>
                                	</a> 
                                	<form id="destroy-form" action="{{ route('cars.destroy',$car->id) }}" method="POST" style="display: none;">
                                		<input type="hidden" name="_method" value="DELETE">
										<input type="hidden" name="_token" value="{{ csrf_token() }}">
                                	</form> -->
	                          	</td>	                         
	                        </tr> 
	                        @php
		                        $i++;
		                    @endphp 
                        @endforeach
                      </tbody>
                    </table>
                	</br>
                    <div class="row">
                    	<div class="col-md-4">
                    		<mark class="bg-info text-white">Total Records : {{$count}} </mark>
                    	</div>
                    	<div class="col-md-4">
                    		{{ $cars->links() }}
                    	</div>
                    	<div class="col-md-4">
                    		<mark class="bg-warning text-white">Current Page : {{$cars->currentPage()}} </mark>
                    	</div>

                    </div>                    
                    <!-- {!! $cars->render() !!} -->
                   <!--  <div class="row">
                    	<div class="col-md-4 col-md-offset-4">
                    		{{ $cars->links() }}
                    	</div>
                    	
                    </div> -->
                  </div>
                </div>
            </div>
		</div>
	
    <!-- partial -->       
@include('admin.layouts.common.footer')
<style type="text/css">
	.pagination li {
		height:20%;
		width:30%;
		border:1px solid #123;
		background-color: #19d895 ;
		color: #ffffff;
		text-align: center;
		font-size: 15px;
		margin: 0 3px 0 0;
		cursor: not-allowed;
	}	
</style>
<script type="text/javascript">
	$('.veiwCar').click(function(){
		var url = $(this).data('url');
		$.ajax({
				type:'GET',
				url:url,
				//data:{"_token": "{{ csrf_token() }}"},
				success:function(data){           
				console.log(data);
				var html = `<table class="table">                      
                      <tbody>
                      	<tr>
                      		<td>Brand</td>
                      		<td>`+data.car.car_brand+`</td>
                      	</tr>
                      	<tr>
                      		<td>Name</td>
                      		<td>`+data.car.car_name+`</td>
                      	</tr>
                      	<tr>
                      		<td>Image</td>
                      		<td class=""><img src="{{URL('assets/car')}}/{{"`+data.car.car_image+`"}}" alt="image">
                      		</td>
                      	</tr>
                      	<tr>
                      		<td>Price</td>
                      		<td>`+data.car.car_price+`</td>
                      	</tr>
                      	<tr>
                      		<td>Created At</td>
                      		<td>`+data.car.created_at+`</td>
                      	</tr>
                      	<tr>
                      		<td>Updated At</td>
                      		<td>`+data.car.updated_at+`</td>
                      	</tr>                        
                      </tbody>
                    </table>`;
				$(".modal-title").html('Car Information');
				$(".modal-body").html(html);
				$(".modal").modal('show');
				
			}
		});
	});
</script>